#!/usr/bin/env bash

# Function to query DNS and display information
display_info() {
	local subdomain=$1
	local domain=$2
	
	dig_result=$(dig $subdomain.$domain | awk '/^;; ANSWER SECTION:$/,/^$/' | awk 'NR>1')
	record_type=$(echo "$dig_result" | awk '{print $4}')
	destination=$(echo "$dig_result" | awk '{print $5}')
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}
# Main function
main() {
	local domain=$1
	local subdomain=$2
	
	if [ -z "$subdomain" ];
	then
		subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in "${subdomains[@]}"; do
			display_info "$sub" "$domain"
		done
	else
		display_info "$subdomain" "$domain"
	fi
}

# Execute main function with provided arguments
main "$@"

