#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server:

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/
fi
