#!/usr/bin/env bash
#Install, config, and start web server Nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
service nginx start
echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
