#!/usr/bin/env bash
#Install, config, and start web server Nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
service nginx start
echo "<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>" | sudo tee /var/www/html/index.htmlufw allow 'Nginx HTTP'

sudo service nginx restart
