#!/usr/bin/env bash
#Install, config, and start web server Nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
