#!/usr/bin/env bash
#Nginx must running,listening on port 80 of all server’s active IPv4 IPs
echo "server { listen 80; }" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

