#!/usr/bin/env bash
#Nginx running,listening on port 80 of all server’s active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
