#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.
#script should only display: username, user id, Home directory path for the user
#using while loop

f="/etc/passwd"
while IFS=read -r l
do
echo "$l | cut -d":" -f1,3,6
done < "$f"
