#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
#using awk

file="apache-access.log"
if test -f $file
then
	awk '{print $1,$9}' $file | sort | uniq -c | sort -gr
fi
