#!/usr/bin/env bash
#script to print with while loop and if, elif, else conditioin

counter=0
while [ $counter -lt 10 ]
do
	if [ $counter -eq 3 ]
	then
		echo "bad luck"
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
