#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 1 to 59
#using while loop
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((h++))
done
