#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01
#Configure ufw so that it blocks all incoming traffic,
#except the following TCP ports:22/tcp , 443/tcp, 80/tcp

sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status verbose
sudo ufw enable
